### ISSUE TITLE
tor crashes on OS X 10.11.6 / Ricochet 1.1.4

### ISSUE THREAD

**Issue by taoeffect** [ricochet-im/ricochet#480]
The Tor tab shows: **Process crashed**

```
dyld: lazy symbol binding failed: Symbol not found: _getentropy
Referenced from: /Applications/Ricochet.app/Contents/MacOS/tor
Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _getentropy
Referenced from: /Applications/Ricochet.app/Contents/MacOS/tor
Expected in: /usr/lib/libSystem.B.dylib
```

Crash report attached: **[tor_2016-11-07.crash.zip](https://github.com/ricochet-im/ricochet/files/577186/tor_2016-11-07.crash.zip)**

**Comment by special** [comment]
This week in "Apple did something weird with XCode..."

> OS Version:            Mac OS X 10.11.6

Looks like `_getentropy` was added in 10.12, and Tor automatically picked it up. That is strange: we build with `-mmacosx-version-min=10.7`, which should hide newer symbols.

Investigating further. Workarounds are to update to Sierra, replace `Ricochet.app/Contents/MacOS/tor` with another tor binary and make codesign stop screaming, or remove that file and put a `tor` in `$PATH` (and maybe also make codesign stop screaming).

**Comment by taoeffect** [comment]
Awesome, to help others with the workaround:

1. Install [Homebrew](https://github.com/Homebrew/brew/) and get it setup / updated
2. `brew install tor`
3. Then in a **new terminal window** (or after running `rehash` to detect new `tor` binary):

```
cd /Applications/Ricochet.app/Contents/MacOS
rm -f tor
ln -s $(which tor)
```

Works like a charm. Oddly enough there was no complaint when I launched it via the Dock again... even though I have GateKeeper set to allow only from Mac App Store and identified developers... Perhaps because I already launched it once? (Is this a security bug in OS X that I just discovered?)

**Comment by special** [comment]
macOS SDK bug: `<sys/random.h>` is supposed to have an `__OSX_AVAILABLE_STARTING` macro for getentropy.

This is going to require patching tor in the build, which is something I prefer to avoid, but.. :/

**Comment by special** [comment]
Rebuilt with that patch. Please give this a try and let me know if it works:

https://ricochet.im/releases/1.1.4/ricochet-1.1.4.1-macos.dmg
https://ricochet.im/releases/1.1.4/ricochet-1.1.4.1-macos.dmg.asc

**Comment by taoeffect** [comment]
Fixed something, still broken:

```
Nov 07 20:02:08.731 [notice] Tor v0.2.8.9 running on Darwin with Libevent 2.0.22-stable, OpenSSL 1.0.2j and Zlib 1.2.5.
Nov 07 20:02:08.732 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Nov 07 20:02:08.733 [notice] Read configuration file "/Users/[user]/Library/Application Support/Ricochet/Ricochet/tor/default_torrc".
Nov 07 20:02:08.733 [notice] Read configuration file "/Users/[user]/Library/Application Support/Ricochet/Ricochet/tor//torrc".
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /Applications/Ricochet.app/Contents/MacOS/tor
Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _clock_gettime
Referenced from: /Applications/Ricochet.app/Contents/MacOS/tor
Expected in: /usr/lib/libSystem.B.dylib
```

**[tor_2016-11-07.crash.zip](https://github.com/ricochet-im/ricochet/files/577264/tor_2016-11-07.crash.zip)**

**Comment by special** [comment]
> Rebuilt with that patch. Please give this a try and let me know if it works:

> https://ricochet.im/releases/1.1.4/ricochet-1.1.4.1-macos.dmg
> https://ricochet.im/releases/1.1.4/ricochet-1.1.4.1-macos.dmg.asc

Please try again, same links. To make sure:

```
$ shasum -a 256 ricochet-1.1.4.1-macos.dmg
e5fbcbebe51fa52d9443fd2a07714d0e6e087c314a9c3eecf73ed4da8ca9e8aa  ricochet-1.1.4.1-macos.dmg
```

**Comment by taoeffect** [comment]
Hey that worked! 😄

**Comment by special** [comment]
Great! I updated the GitHub release and website with the new link. Should be solved now. Thanks!
